"""Added used_id feild

Revision ID: 484eefd3aac0
Revises: bf6734727d7b
Create Date: 2026-09-26 18:53:54.319705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484eefd3aac0'
down_revision: Union[str, Sequence[str], None] = 'bf6734727d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercise_library', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'exercise_library', type_='foreignkey')
    op.drop_column('exercise_library', 'user_id')
    # ### end Alembic commands ###
