"""add equipement to library table

Revision ID: 48de645d8d0c
Revises: 484eefd3aac0
Create Date: 2026-10-01 23:00:32.192223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48de645d8d0c'
down_revision: Union[str, Sequence[str], None] = '484eefd3aac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('equipement', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_library', 'equipement')
    # ### end Alembic commands ###
