"""Update worksouts models

Revision ID: bf6734727d7b
Revises: d9cf6e3de4d7
Create Date: 2026-09-26 18:50:12.006664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6734727d7b'
down_revision: Union[str, Sequence[str], None] = 'd9cf6e3de4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('valid_splits', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('wokout_sessions', sa.Column('schedule', sa.String(), nullable=False))
    op.alter_column('wokout_sessions', 'split_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_wokout_sessions_schedule'), 'wokout_sessions', ['schedule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wokout_sessions_schedule'), table_name='wokout_sessions')
    op.alter_column('wokout_sessions', 'split_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('wokout_sessions', 'schedule')
    op.drop_column('exercise_library', 'valid_splits')
    # ### end Alembic commands ###
