"""Workouts table created

Revision ID: d9cf6e3de4d7
Revises: 9ee23c21c9ee
Create Date: 2026-09-26 10:52:27.719614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cf6e3de4d7'
down_revision: Union[str, Sequence[str], None] = '9ee23c21c9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('targeted_muscle', sa.String(length=50), nullable=False),
    sa.Column('recovery_time_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_library_id'), 'exercise_library', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_library_name'), 'exercise_library', ['name'], unique=True)
    op.create_index(op.f('ix_exercise_library_targeted_muscle'), 'exercise_library', ['targeted_muscle'], unique=False)
    op.create_table('wokout_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('split_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wokout_sessions_id'), 'wokout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_wokout_sessions_split_type'), 'wokout_sessions', ['split_type'], unique=False)
    op.create_table('workout_exercise_logs',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_name'], ['exercise_library.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['wokout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercise_logs_id'), 'workout_exercise_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_logs_id'), table_name='workout_exercise_logs')
    op.drop_table('workout_exercise_logs')
    op.drop_index(op.f('ix_wokout_sessions_split_type'), table_name='wokout_sessions')
    op.drop_index(op.f('ix_wokout_sessions_id'), table_name='wokout_sessions')
    op.drop_table('wokout_sessions')
    op.drop_index(op.f('ix_exercise_library_targeted_muscle'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_name'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_id'), table_name='exercise_library')
    op.drop_table('exercise_library')
    # ### end Alembic commands ###
